version: '3'

services:
  db:
    image: postgres
  cache:
    image: redis
  web:
    build: .
    command: ./init.sh
    volumes:
    - .:/code
    ports:
    - 8000:8000
    environment:
    - CACHE_HOST=cache
    - CACHE_PORT=6379
    - CACHE_TTL=10
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_HOST=db
    - DB_PORT=5432
    depends_on:
    - db
    - cache
